server:
  port: 0
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: my-first-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
